### ISSUE TITLE
Missing function ws2struct

### ISSUE THREAD

**Issue by yakunsjtu** [marco-faroni/TrajectoryScaling#1]
Hi @marco-faroni , I tried to run the script, but could not find the following functions:

- ws2struct called in the import_robot.m file
- mycolnorm in taskdata.m (line 42) 
- mygradient in DJDQ.m (line 11)

Could you help to fix it? Thanks!

**Comment by marco-faroni** [comment]
Hi @yakunsjtu, I've added the missing functions!

**Comment by yakunsjtu** [comment]
Thank you @marco-faroni, I already updated the new package then I found the function _vectorizedFcn_ in DJDQ.m (line 10) and the function _plotLine_ in compute_error (line 62) were also undefined.Could you add it? 

BTW, does the function DJDQ try to solve the JdotQdot iterm in the dynamic equation?

**Comment by marco-faroni** [comment]
@yakunsjtu I've added them.
Yes, it computes JdotQdot given a joint position and velocity vector. I think I need it only to use the look-ahead method described in https://www.sciencedirect.com/science/article/abs/pii/S0094114X20303694

**Comment by yakunsjtu** [comment]
Thanks @marco-faroni. Now I ran all the examples successfully. 
I noticed in the file robots/ur10/dynamics_matrix_ur10_HCBF.m (line 39), the last element of the mass matrix was multiplied by 10. Why not use the original mass matrix?

**Comment by marco-faroni** [comment]
Hi. We just found out that the original values were unrealistic when we used them for real experiments. I don't know why I used 10, I guess I just tried to increase the value until the tracking performance looked similar to experimental results (despite it is not the cleanest solution...)
