### ISSUE TITLE
About the cost function

### ISSUE THREAD

**Issue by yakunsjtu** [marco-faroni/TrajectoryScaling#2]
Hey @marco-faroni , I went through the Matlab code and try to compare the implemented algrothom with the following paper: Predictive joint trajectory scaling for manipulators with kinodynamic constraints.

In the file controllers/thor/ctrl_law.m (line 156), I was confused by these intermediate matrixes:

`
  Heq = [ctrl.F(:,:,2)+[ctrl.Kclik*ctrl.F(1:df,:,1);0*ctrl.F(df+1:end,:,1)], -diag(qd_des)*ctrl.PD; zeros(Ns,Np*df), eye(Ns)]
`

`
H = Heq'*ctrl.Wsc*Heq  + ctrl.lambdaU*ctrl.Hu;
`

`
f = -[ -(ctrl.L(:,:,2) + [ ctrl.Kclik*ctrl.L(1:df,:,1);0*ctrl.L(df+1:end,:,1)] )*q0 + [ctrl.Kclik*qdes; zeros(df*(Np-1),1)] ; s_ref.*ones(Ns,1) ]'*ctrl.Wsc*ctrl.Hp*Heq;
`

And finally the Hessian matrix is computed:
`
HH = (H+H')/2;
`

But I could not figure out the underlying theory and the paper did not mention it, I only found out the cost function in the paper like this:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/28284575/140472644-405160cf-5dd9-4c7c-881d-962fc849be93.png">

From the figure, the weighting matrixes are Q, R and P. But how these 3 matrixes correspond to the matrixes in the code then (how to transform the cost function to the code format)?  And what are the matlab variables corresponding to these 4 variables in the equation?

<img src="https://latex.codecogs.com/svg.latex?\dot{q}(k&plus;i),&space;{q_{d}}'(s(k&plus;i))),&space;q_{d}(s(k&plus;1)),&space;q(k&plus;1)" title="\dot{q}(k+i), {q_{d}}'(s(k+i))), q_{d}(s(k+1)), q(k+1)" />

**Comment by marco-faroni** [comment]
@yakunsjtu this implementation is slightly different from the equation of the paper, but they are almost equivalent. Matrices ctrl.F and ctrl.L are the forced and free response of a double integrator system (see paper [2] in the references for the math). In practice, ctrl.L(:,:,2)*q0 + ctrl.F(1:df,:,2)*u is equal to qdot(k+i) for i=1...p, where q0 is the current state (q(k),qdot(k)) and u is the optimization variable (qddot). In the code, the third term of the cost function is not present, as I put the position error into the first term. So, Q is equivalent to ctrl.Wsc and R is equivalent to ctrl.Hu. P is not present in the code, Kclik has a similar role; more or less it should be P=(Kclik^2)*Wsc(1:df,1:df)

**Comment by yakunsjtu** [comment]
Thanks @marco-faroni , after reading the paper you mentioned, I'm much clear about the prediction method. As for the construction of the QP problem, do you mean the following procedure:

Firstly, merge the third iterm into the first one, and let <a href="https://www.codecogs.com/eqnedit.php?latex=\small&space;\dot{q}(k&plus;i)-{q_{d}}'(s(k&plus;i)),&space;1-v(k&plus;i),&space;q_{d}(s(k&plus;1))-&space;q(k&plus;1)" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\small&space;\dot{q}(k&plus;i)-{q_{d}}'(s(k&plus;i)),&space;1-v(k&plus;i),&space;q_{d}(s(k&plus;1))-&space;q(k&plus;1)" title="\small \dot{q}(k+i)-{q_{d}}'(s(k+i)), 1-v(k+i), q_{d}(s(k+1))- q(k+1)" /></a>, the cost function is <a href="https://www.codecogs.com/eqnedit.php?latex=\small&space;f=a^{T}Qa&plus;u^{T}Ru" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\small&space;f=a^{T}Qa&plus;u^{T}Ru" title="\small f=a^{T}Qa+u^{T}Ru" /></a>, and the we expand the item to get those intermediate matrices? But I feel not easy to do the math to separate out the optimization variable. If this is the right way, I will try again to do it.

**Comment by yakunsjtu** [comment]
BTW, could this formulation enforce the joint acceleration to be zero at start and end of trajectory? I did a test using the following settings:
`robot_name='ur10';`
`method='thor'; `
`task_space='joint'; `
`path='sine'; `
`timinglaw='polynomial'; `
`model='kinematic'; `

However, at the first cycle, the ddq_ctrl gives a value to be 
[2.50816412131200
5
5.85238294972811
5.43435559617611
6.27041030328006
6.68843765683202],
And the first figure is shown below which seems to have a large error:
![image](https://user-images.githubusercontent.com/28284575/140631252-ea30a885-098a-47f6-a007-d26a45707fb8.png)
 Is this a normal behavior or should I tune some parameters?

**Comment by marco-faroni** [comment]
From the paper, the objective function in Eq. 16 is composed of three terms, the first one accounts for path following (at velocity level), the second one accounts for effort, the third one for position error. These three terms can be seen as squared norms of vectors. Now consider such three vectors and sum (instead of concatenating) the first one and the third one and then derive the cost function.
