### ISSUE TITLE
Jerk level constraints

### ISSUE THREAD

**Issue by yakunsjtu** [marco-faroni/TrajectoryScaling#3]
Hi @marco-faroni , I tried to set **order = 3** in the file controllerdata.m (line 55), but the script seems fail to run. I'm wondering if this framework could support jerk level constraints? Because it would be very helpful for robot like KUKA-iiwa with flexible joints. Hope to have this feature included ^_^

**Comment by marco-faroni** [comment]
Hello, from a mathematical point of view it is possible. However, the functionality is not implemented here. Unfortunately, I don't plan to modify the code. It was just meant to provide some code snippets to help in the implementation of the referenced paper.
